version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/registration-processor/mosip-stage-executor" 
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 50
